name: flight_reminder
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  cupertino_icons: ^1.0.2

  lottie: ^2.5.0

  flutter_svg: ^2.0.7

  sqflite: ^2.3.0

  path: ^1.8.3

  provider: ^6.0.5

  shared_preferences: ^2.2.0

  encrypt: ^5.0.1

  get_it: ^7.6.0

  firebase_messaging: ^14.6.6

  firebase_core: ^2.15.1

  event_bus: ^2.0.0

  fluttertoast: ^8.2.2

  flutter_local_notifications: ^15.1.0+1

  loading_indicator: ^3.1.1

  http: ^1.1.0

  connectivity_plus: ^4.0.2

  firebase_crashlytics: ^3.3.5

  share_plus: ^7.1.0

  syncfusion_flutter_pdfviewer: ^23.1.39


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/
    - assets/onboarding_assets/
